site_name: IQ Script
theme:
    logo: assets/logo.png
    favicon: assets/favico2.ico
    language: pt
    name: material
    font:
        code: Roboto Mono
    features:
        - navigation.instant
        - navigation.tracking
        - navigation.tabs
        - navigation.expand
        - navigation.sections
        - navigation.top
        - toc.integrate
        - navigation.indexes
        - search.suggest
        - search.share
        
    palette:
        scheme: slate
        primary: teal
        accent: light green
        
nav:
    - Inicio: index.md
    - Configurações: config.md
    - Metodos suportados: diferencas.md
    - Como proteger seu Script/Indicador: key.md
    - Exemplos: exemple.md


extra_css:
    - stylesheets/extra.css


markdown_extensions:
    - attr_list
    - meta
    - admonition
    - pymdownx.details
    - pymdownx.superfences    
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.highlight
    - pymdownx.critic
    - pymdownx.caret
    - pymdownx.keys
    - pymdownx.mark
    - pymdownx.tilde
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
    

extra:
    social:
        - icon: fontawesome/brands/telegram
          link: https://t.me/iqcoding_vip
          name: IQ Coding no Telegram
          
        - icon: fontawesome/brands/youtube
          link: https://youtube.com/c/iqcoding
          name: IQ Coding no YouTube
    
    version:
        provider: 0.8
    
copyright: Copyright &copy; 2021 - IQ Coding